### PR TITLE
feat: adding project's Dockerfile

### PR DESCRIPTION
**Pull request by machad0**
discussion at #1

### CODE REVIEW

**Review by raphaklaus — CHANGES_REQUESTED** [review]
I don't see `deps.get` command inside `Dockerfile`.

**Comment by machad0** [comment]
Well, since we're running it inside a container, the command need to be non-interactive, like the instructions from the printscreen at #1 points to:
`if running non-interactively, use mix local.hex --force`

Otherwise, it can cause errors since there's no passthrough flag.

**Edit: 
Ok, just noticed the error. didn't saw it before probably because of some cached stuff. I thought that `local.hex` and `compile` would be enough. I'll fix the PR ASAP.

**Comment by raphaklaus** [comment]
Exactly.

Also, I recommend using `mix clean` before `mix deps.get` to ensure everything is fresh and clean.

**Comment by raphaklaus** [comment]
Hi,

any update on this?

**Comment by raphaklaus** [comment]
Closing as it has been moved to JS/TS

**Pull request closed without merging**
